---
- name: Provision Production Server
  hosts: sovereign
  become: yes
  tasks:
    # Good security practice to create non-root 
    # user and then not allow root to ssh.
    - name: Create deploy user on server
      user: >
        name=deploy
        shell=/bin/bash
        group=sudo

    - name: Copy SSH key to allow logins with no password
      authorized_key: >
        user=deploy
        key="{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Skip sudo password for new user
      lineinfile: >
        dest=/etc/sudoers
        line="deploy ALL=(ALL) NOPASSWD:ALL"
        validate='visudo -cf %s'

    - name: Disable root ssh login
      lineinfile: >
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin yes' line='PermitRootLogin no'
        state=present

    - name: Restart ssh server
      command: /etc/init.d/ssh restart
